cursor #dfe3e9
cursor_text_color #bec7d3

foreground            #dfe3e9
background            #0f1418
selection_foreground  #05334f
selection_background  #a5cbed
url_color             #91cdff

color0   #0f1418
color1   #ff729d
color2   #7fff8f
color3   #fff772
color4   #74b9f2
color5   #184b76
color6   #91cdff
color7   #eff8ff
color8   #99a0a5
color9   #ff9fbc
color10  #a5ffb1
color11  #fffaa5
color12  #a1d4ff
color13  #b2dbff
color14  #cde8ff
color15  #f8fcff
