# Minimal Mango config

# execs
exec-once=swaybg -i ~/Pictures/Wallpapers/hd-Jellyfish_upscayl_4x_upscayl-standard-4x.jpg -m fill
exec-once=syshud
exec=pkill waybar; waybar

# keyboard
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us
xkb_rules_variant=altgr-intl
xkb_rules_options=caps:swapescape

# pointer / touchpad
tap_to_click=1
tap_and_drag=1
drag_lock=1
disable_while_typing=1
mouse_natural_scrolling=0
trackpad_natural_scrolling=0

# appearance / behavior
borderpx=2
gappih=0
gappiv=0
gappoh=0
gappov=0
focus_on_activate=1
sloppyfocus=0
warpcursor=0
drag_tile_to_tile=1

# monitors
monitorrule=name:^eDP-1$,width:1920,height:1200,refresh:120,x:0,y:0,scale:1,rr:0
monitorrule=name:^DP-2$,width:2560,height:1440,refresh:120,x:1920,y:0
monitorrule=name:^HDMI-A-1$,x:4480,y:0

# effects
blur=1
blur_layer=1
blur_optimized=0
blur_params_num_passes=3
blur_params_radius=5
blur_params_noise=0.02
blur_params_brightness=1
blur_params_contrast=1
blur_params_saturation=1

# layout
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# core binds
bind=ALT,Return,spawn,wezterm
bind=SUPER,r,reload_config
bind=SUPER,m,togglefullscreen
bind=SUPER,n,togglescratchpad
bind=SUPER+CTRL,q,quit
bind=SUPER,q,killclient,
bind=SUPER,space,spawn,fuzzel
bindr=SUPER,,spawn,fuzzel

# focus windows
focus_cross_monitor=1
exchange_cross_monitor=1
bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=SUPER,l,focusdir,right
bind=SUPER,Tab,focusstack,next

# move / swap windows
bind=SUPER+SHIFT,h,tagmon,left
bind=SUPER+SHIFT,j,tagmon,down
bind=SUPER+SHIFT,k,tagmon,up
bind=SUPER+SHIFT,l,tagmon,right

# window state
bind=ALT,Tab,toggleoverview,
bind=SUPER,x,toggleoverview,
bind=ALT,backslash,togglefloating,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,

# brightness
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +2%
bind=SHIFT,XF86MonBrightnessUp,spawn,brightnessctl s 100%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 2%-
bind=SHIFT,XF86MonBrightnessDown,spawn,brightnessctl s 1%

# volume
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# workspaces
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# mouse bindings
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=NONE,btn_left,toggleoverview,1
mousebind=NONE,btn_right,killclient,0
