dpi-aware=no
namespace=fuzzel
icon-theme=Papirus-Dark
width=55
font=Hack:weight=normal:size=16
line-height=28
fields=name,generic,comment,categories,filename,keywords
terminal=wezterm
prompt="❯   "
show-actions=yes
exit-on-keyboard-focus-loss=no
inner-pad=10
list-executables-in-path=true
anchor=bottom-right
lines=20
keyboard-focus=on-demand
exit-on-keyboard-focus-loss=true


include=~/.config/fuzzel/themes/noctalia
; theme color overrides:
[colors]
background=121316aa
text=e3e2e6aa
border=a5c8ff22
selection=a5c8ff33

[border]
radius=15
selection-radius=5
width=2


[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
delete-line-forward=none
prev=Control+k Up
next=Control+j Down
