# suppress "Press enter to return to lazygit" in lazyvim
promptToReturnFromSubprocess: false
# git:
#   pagers:
#     - colorArg: always
#       pager: delta --paging=never --features catppuccin-mocha --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --line-numbers --hyperlinks
