
# SYSTEM =======================================================================
source = modules/displays.conf
source = modules/input.conf
source = modules/exec-once.conf

# BINDS ======================================================================== 
source = modules/binds.conf

# AESTHETICS ===================================================================
source = modules/colors.conf
source = modules/decorations.conf
source = modules/groups.conf
misc {
  disable_hyprland_logo = true # disables hyprland wallpaper on start
  # disable_splash_rendering = true
}

# PLUGINS ======================================================================
# plugin = /home/daniel/.nix-profile/lib/libhyprbars.so
# plugin = /home/daniel/.nix-profile/lib/libhyprexpo.so
# plugin = /home/daniel/.nix-profile/lib/libhyprspace.so
# source = modules/hyprbars.conf
# source = modules/hyprexpo.conf
