return {
  --   "neovim/nvim-lspconfig",
  --   opts = {
  --     servers = {
  --       tailwindcss = {
  --         filetypes_include = { "heex", "leex", "eex", "ex" },
  --       },
  --     },
  --     setup = {
  --       tailwindcss = function(_, opts)
  --         local tw = LazyVim.lsp.get_raw_config("tailwindcss")
  --         opts.filetypes = opts.filetypes or {}
  --
  --         vim.list_extend(opts.filetypes, tw.default_config.filetypes)
  --
  --         opts.settings = {
  --           tailwindCSS = {
  --             includeLanguages = {
  --               elixir = "html-eex",
  --               eelixir = "html-eex",
  --               heex = "html-eex",
  --             },
  --           },
  --         }
  --
  --         -- Add additional filetypes
  --         vim.list_extend(opts.filetypes, opts.filetypes_include or {})
  --       end,
  --     },
  --   },
}
