# default config:
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

[mgr]
show_hidden = true

# [opener]
# play = [
#     { run = 'vlc "$@"', desc = "VLC", orphan = true }
# ]
